repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
      - id: check-json
      - id: check-toml
      - id: check-yaml
      - id: end-of-file-fixer
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: "ffb6a759a979008c0e6dff86e39f4745a2d9eac4"
    hooks:
      - id: prettier
        types_or: [css, html, javascript]
  - repo: local
    hooks:
      - id: commitizen
        name: commitizen
        entry: uvx cz check
        args: [--commit-msg-file]
        require_serial: true
        language: system
        stages: [commit-msg]
      - id: ruff
        name: ruff
        entry: uvx ruff
        args: ["check", "--extend-fixable=F401,F841", "--fix-only"]
        require_serial: true
        language: system
        types: [python]
      - id: ruff
        name: ruff-fmt
        entry: uvx ruff
        args: ["format"]
        require_serial: true
        language: system
        types: [python]
      - id: mypy
        name: mypy
        entry: uv run mypy
        language: system
        types: [python]
      - id: sqlfluff
        name: sqlfluff-fmt
        entry: uvx sqlfluff
        args: ["format", "--dialect", "sqlite"]
        language: system
        types: [python]
      - id: sqlfluff
        name: sqlfluff-lint
        entry: uvx sqlfluff
        args: ["lint", "--dialect", "sqlite"]
        language: system
        types: [python]
