version: '3.8'
services:
  editio:
    build:
      dockerfile: Dockerfile
      context: .
      args:
        - BUILD_DIR=build
        - KEEP_ATOM_EDITOR=false
    healthcheck:
      test: curl --fail http://localhost:8080/exist/apps/dashboard/index.html || exit 1
      interval: 25s
      retries: 10
      start_period: 20s
      timeout: 450s
    ports:
      - 5600:8080
    environment:
      - EXIST_PASSWORD
      - EXIST_ENV=production
      - VIRTUAL_HOST
      - LETSENCRYPT_HOST
    restart: unless-stopped
    volumes:
      - /opt/exist/data

networks:
  default:
    external: true
    name: ${PROXY_NETWORK}
