[editio]
settings = { env = "prod", cache = "true", index_prefix = "index", upload = "false", urls = { "de" = "ssrq-online.ch", "fr" = "sds-online.ch", "it" = "fds-online.ch", "en" = "sls-online.ch" } }
volumes = [
    { name = "FR_I_2_8", include = "all" },
    { name = "NE_1", include = "sources_only" },
    { name = "NE_3", include = "all" },
    { name = "NE_4", include = "all" },
    { name = "SG_III_4", include = "all" },
    { name = "ZH_NF_I_1_3", include = "all" },
    { name = "ZH_NF_I_1_11", include = "all" },
    { name = "ZH_NF_I_2_1", include = "all" },
    { name = "ZH_NF_II_3", include = "all" },
    { name = "ZH_NF_II_11", include = "all" },
    { name = "VD_D_1", include = "sources_only" },
]


[editio.build]
volumes = { source = "data/tei-volumes", target = "editio-data" }
misc_data = { source = "data/tei-volumes/misc", target = "editio-data/misc" }
css = { source = "eXist_app/resources/css/src/main.css", target = "eXist_app/resources/css/style.css" }
expath = "eXist_app/expath-pkg.xml"
prod_ignores = [
    "eXist_app/modules/lib/regenerate.xql",
    "eXist_app/modules/pub/upload.xql",
    "eXist_app/templates/upload.html",
    "eXist_app/routes/temp.html",
]
common_ignores = [
    ".DS_Store",
    ".git",
    "Dockerfile",
    "Dockerfile.dev",
    "docker-compose.dev.yml",
    "docker-compose.yml",
    "eXist_app/build.xml",
    ".existdb.json",
    "editio_config.toml",
    "pyproject.toml",
    "poetry.lock",
    "README.md",
    "build",
    "cli",
    "data",
    "eXist_app/resources/css/src",
    "tests",
    "eXist_app/transform",
]

[editio.docker]
dev = { compose_file = "docker-compose.dev.yml", user = "admin", password = "ssrq", port = "8080" }
