"""MCP server configuration for the SSRQ/Editio application."""

from fastmcp import FastMCP

from ssrq_editio.entrypoints.app.shared.dependencies import db_connection
from ssrq_editio.models.search import DocumentSearchResponse
from ssrq_editio.services.search import search_documents as search_documents_service

MCP_CACHE_TTL_SECONDS = 180 * 60

mcp: FastMCP = FastMCP(
    name="SSRQ · SDS · FDS / Editio",
    instructions=(
        "Use this server to explore the digital scholarly edition of the Swiss Law Sources."
    ),
    cache_ttl=MCP_CACHE_TTL_SECONDS,
)


@mcp.tool
async def search_documents(query: str) -> DocumentSearchResponse:
    """Search the SSRQ/Editio documents with the edition's full-text search.

    Search results include ``keywords`` when editorial semantic metadata was assigned to a
    document. These are editor-assigned entity IDs, not display labels or terms generated by
    the full-text search. Resolve them through the entity interface. The field may be absent
    when no keywords were assigned; this does not imply that the document has no thematic
    relevance.

    Args:
        query: A full-text search expression to look up in the edition.

    Returns:
        The query, all matching documents, and their total number of results.
    """
    async for connection in db_connection():
        return await search_documents_service(connection=connection, query=query)

    raise RuntimeError("The database session did not yield a connection.")

# The ASGI application is created once and mounted into the existing FastAPI application.
# Its lifespan is passed to FastAPI so that FastMCP can initialize its HTTP session manager.
mcp_app = mcp.http_app(path="/", transport="streamable-http")
