name: Release editio data

on:
  workflow_dispatch:
    inputs:
      data_version:
        description: 'The Version of the data to release'
        type: string
        required: true
      schema_url:
        description: 'The URL of the schema used to validate the data'
        type: string
        required: true
        default: 'https://schema.ssrq-sds-fds.ch/'
      schema_version:
        description: 'The version of the schema used to validate the data'
        type: string
        required: true
        default: 'latest'

jobs:
  copy-and-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout src repo
        uses: actions/checkout@v4
        with:
          path: 'src'
          persist-credentials: false
          submodules: 'recursive'
          token: ${{ secrets.TEI_VOLUMES_PAT }}
      - name: Install poetry
        shell: bash
        run: pipx install poetry
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
          cache: 'poetry'
      - name: Install dependencies
        shell: bash
        run: poetry install -C src
      - name: Create data bundle
        shell: bash
        run: |
          poetry run -C src editio build 'prod'
          rm -rf src/editio-data/misc
          echo -e "${{ inputs.schema_url }}${{ inputs.schema_version }}" > src/editio-data/.schema
          echo "Using schema pointing to $(cat src/editio-data/.schema)"
      - name: Push data bundle
        uses: cpina/github-action-push-to-another-repository@main
        env:
          SSH_DEPLOY_KEY: ${{ secrets.DATA_DEPLOY }}
        with:
          commit-message: 'Release data version ${{ inputs.data_version }}'
          destination-github-username: 'SSRQ-SDS-FDS'
          destination-repository-name: 'editio-data'
          source-directory: 'src/editio-data'
          target-branch: main
          target-directory: 'data'
          user-email: ${{ secrets.DATA_RELEASE_MANAGER_MAIL }}
          user-name: ${{ secrets.DATA_RELEASE_MANAGER_NAME }}
      - name: Checkout dest repo for tagging
        uses: actions/checkout@v4
        with:
          repository: 'SSRQ-SDS-FDS/editio-data'
          path: 'dest'
          persist-credentials: false
          ref: 'main'
          ssh-key: ${{ secrets.DATA_DEPLOY }}
      - name: Tag data release
        shell: bash
        env:
          SSH_AUTH_SOCK: /tmp/ssh_agent.sock
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan github.com >> ~/.ssh/known_hosts
          ssh-agent -a $SSH_AUTH_SOCK > /dev/null
          ssh-add - <<< "${{ secrets.DATA_DEPLOY }}"
          cd dest
          git config user.name "${{ secrets.DATA_RELEASE_MANAGER_NAME}}"
          git config user.email "${{ secrets.DATA_RELEASE_MANAGER_MAIL }}"
          git tag -a "${{ inputs.data_version }}" -m "Release data version ${{ inputs.data_version }}"
          git push --follow-tags
